export * as ProductShopifyService from './product'
export * as ColletionShopifyService from './collection'
export * as FixedOffersShopifyService from './fixed-offers'
export * as ColorsShopifyService from './color'
export * as HeroBannersShopifyService from './hero-banners'